### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Authentication.SharedAuthenticationOptions'

### ISSUE THREAD

**Issue by ebrand** [SteeltoeOSS/Security#1]
Hey guys,

I realize I may be on the bleeding edge here with ASP.NET Core 2.0, but perhaps you guys have come across this:

`Could not load type 'Microsoft.AspNetCore.Authentication.SharedAuthenticationOptions' from assembly 'Microsoft.AspNetCore.Authentication, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

Here's the stack trace:

```
   at Steeltoe.Security.Authentication.CloudFoundry.CloudFoundryServiceCollectionExtensions.AddCloudFoundryAuthentication(IServiceCollection services, IConfiguration config)
   at WhoAreYou.Startup.ConfigureServices(IServiceCollection services) in C:\Users\eric_brand\Source\Repos\WhoAreYou\WhoAreYou\Startup.cs:line 25
```

Is this a Pebkac situation or something you've experienced and are working on a fix for? Any help you can provide would be greatly appreciated. 

Thanks,
Eric

**Comment by ReneHerrero** [comment]
I'm experiencing the same issue on my end.

**Comment by dtillman** [comment]
Hi,
Yes, support for ASP.NET 2.0 was a problem... Microsoft changed things significantly in 2.0.
We are adding support for ASP.NET 2.0 in our Steeltoe 2.0 release.  We are targeting December release.

In the mean time, you can get working code off the Steeltoe Dev Nuget feed, if your interested in testing it out.  

https://myget.org/feed/steeltoedev/package/nuget/Steeltoe.Security.Authentication.CloudFoundryCore

Use latest version and if you have any problems ... let me know and I'll be glad to help.

Dave
