### ISSUE TITLE
SSO Behind a Reverse Proxy

### ISSUE THREAD

**Issue by ReneHerrero** [SteeltoeOSS/Security#2]
Hi,

I'm struggling trying to use the PCF SSO provider behind a reverse proxy.

In the 302 response to the client, I somehow need to swap out the auth domain to something that is externally routable but can't see how to do so.

I did find that is it possible to override the defaults in the ASP.NET Core pipeline (from what I could tell), but it doesn't get picked up:
`
            app.UseCloudFoundryAuthentication(new CloudFoundryOptions
            {
                AuthorizationEndpoint = "https://pcf-sso.somedomain.com"                 
            });
`

Anyone come across this scenario?

Thanks,

René

**Comment by dtillman** [comment]
@ReneHerrero:
Sorry to take so long to get after this... are you still having issues ?

Dave

**Comment by ReneHerrero** [comment]
Yup.  We created a ticket for the issue and where told we need to put reverse and forward proxies.  The latter is very problematic as it would a tremendous amount of overhead...
Maybe I'm missing something, but wouldn't adding an "override default route" option to the SSO tile be warranted?  I'm tempted to think it wouldn't be that hard to develop?  Surely less work than us having implement a whole new SSO provider and the Steeltoe Security equivalent... 
Thanks,

**Comment by dtillman** [comment]
@ReneHerrero
Ok... let me setup SSO and see what I can do from a Steeltoe perspective
Dave

**Comment by dtillman** [comment]
@ReneHerrero 
I've got 1.5.3 of the SSO tile installed.... So, just to make sure I understand the issue you're having with SSO tile...

When you create a SSO service plan, and you are configuring your Auth Domain, you are unable to specify the full URL that would allow you to point to your Reverse Proxy ... is that correct?

Dave

**Comment by jkonicki** [comment]
Reopen if this is still an issue.
