### ISSUE TITLE
Creating a new HttpClient for every request may use all available connections

### ISSUE THREAD

**Issue by sneal** [SteeltoeOSS/Security#5]
[This](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) might be a problem [here](https://github.com/SteeltoeOSS/Security/blob/dev/src/Steeltoe.Security.Authentication.CloudFoundryOwin/TokenExchanger.cs#L64)

**Comment by TimHess** [comment]
You're right, and we're not ignoring this issue, we're just not quite ready to address it yet. We were already planning to refactor this library, it just didn't make it in time for 2.1
